# .github/workflows/chromatic.yml

name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm if not present
        run: |
          if ! command -v pnpm &> /dev/null
          then
            curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          fi

      - name: Install dependencies
        # ⚠️ Pick one of these, matching the package manager for your project
        run: pnpm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}